### ISSUE TITLE
Option to remove / hide the page numbers, xhtml, txt code in reader side list

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#231]
### 1. Red color,
- Please provide an option to remove / hide the page numbers of chapters that are present on the right side of the manga side list.
### 2. Green color,
- Can you increase those right side title and chapter by 2px for both manga and epub.
- Only implement if it looks good.

---

![Option](https://github.com/mienaiyami/yomikiru/assets/127277950/4d3453ae-1404-47c8-b44a-d41b76d8d54c)

**Comment by mienaiyami** [comment]
> ### 1. Red color,
> * Please provide an option to remove / hide the page numbers of chapters that are present on the right side of the manga side list.

Its too small to add an option for it. But you can add the following text at end of your custom stylesheet file.
```css
body #app #reader > div.readerSideList.listCont > div.location-cont > ol > li > a > span.pageNum{
    display: none;
}
```
or this
[noPageNum.zip](https://github.com/mienaiyami/yomikiru/files/12304609/noPageNum.zip)

Same for the green color, you can open the css file in any text editor add the following to end of it.
```css
body #app .reader .readerSideList .in-reader>div>span:not(.bold){
    font-size:1.1em;
}
```
