### ISSUE TITLE
Side list xhtml code for individual xhtml files

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#254]
### Description of the new feature / enhancement

I found the .xhtml code in reader side list to be smothering (for individual .xhtml files).
I know that it works like that.
But can you please provide an option to remove the **xhtml code in reader side list only** it would be great.

---

### Example,

![1](https://github.com/mienaiyami/yomikiru/assets/127277950/50121570-3f8e-4dc1-b955-0156ebe8ac0d)

### Scenario when this would be used?

While reading xhtml files.

### Supporting information

If its possible, please provide an option to remove them for .xhtml in reader side list.

**Comment by mienaiyami** [comment]
you can add this for your custom css file.
```css
body #app div.readerSideList.listCont > div.location-cont > ol > li > a .nonFolder[data-type="XHTML"]{
   display: none;
}
```
I will be creating different section for more style options later so you can use this for now.
